package com;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.ObjectInputStream;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Elhacen
 */
public class Connexion_Admin extends javax.swing.JFrame {
    private final int HAUTEUR;
    private final int LARGEUR;
    private final Dimension staille;
 
    /**
     * Creates new form Connexion
     */
    public Connexion_Admin() {
        initComponents();
        trayIcon = new TrayIcon(image.loadImage("/images/icon.png").getImage());
        staille = Toolkit.getDefaultToolkit().getScreenSize() ;
        HAUTEUR=this.getHeight();
        LARGEUR=this.getWidth();
	setBounds((staille.width-LARGEUR)/2,(staille.height-HAUTEUR)/2-50,this.getWidth(),this.getHeight()) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        bt_Connexion = new javax.swing.JButton();
        erreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Chat");
        setIconImage(image.loadImage("/images/icon.png").getImage());
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.gif"))); // NOI18N
        jLabel1.setText(":");

        name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        name.setText("elhacen");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.gif"))); // NOI18N
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Connexion");

        pass.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        pass.setText("100");

        bt_Connexion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        bt_Connexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.png"))); // NOI18N
        bt_Connexion.setText("Start");
        bt_Connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ConnexionActionPerformed(evt);
            }
        });

        erreur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        erreur.setForeground(new java.awt.Color(204, 0, 0));
        erreur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(pass)
                            .addComponent(bt_Connexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(erreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_Connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ConnexionActionPerformed
        String n=name.getText();
        String p=pass.getText();
	   FileInputStream fichier;
        try {
            fichier = new FileInputStream("Admin.ser");
            ObjectInputStream ois = new ObjectInputStream(fichier);
	    a = (Admin) ois.readObject();
            ois.close();
            } catch (Exception ex) {
            Logger.getLogger(Connexion_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
	     boolean con=a.verifier(n,p);
	    if(con==true){
            try {
                try {
			java.rmi.registry.LocateRegistry.createRegistry(1099);
		} catch (RemoteException e1) {
			
		}
                Server.server=new Server();
                   Naming.rebind("rmi://localhost/Elhacen",Server.server);
                        System.out.println("Server is ready.");
                         SC = new ServerControl(n);
                        this.setVisible(false);
                        SC.setVisible(true);
             } catch (Exception ex) {
                Logger.getLogger(Connexion_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else {
                erreur.setText("User Name Or Password Invalid !");
                pass.setText("");
                pass.requestFocus();
       
			 }
                    
			  
		
    }//GEN-LAST:event_bt_ConnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
        	Properties props = new Properties();
        	 props.put("logoString", "Elhacen Ely"); 
             props.put("licenseKey", "INSERT YOUR LICENSE KEY HERE");
             TextureLookAndFeel.setCurrentTheme(props);
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (Exception ex) {
         } 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               CA= new Connexion_Admin();
               CA.setVisible(true);
                createAndShowGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Connexion;
    private javax.swing.JLabel erreur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
    static ImageHelper image ;
    Admin a =null;
    static ServerControl SC ;
    static Connexion_Admin CA;
    
    
      static TrayIcon trayIcon;
    
   private static void createAndShowGUI() {
        //Check the SystemTray support
        if (!SystemTray.isSupported()) {
            System.out.println("SystemTray is not supported");
            return;
        }
        
        final SystemTray tray = SystemTray.getSystemTray();
        
        MenuItem About = new MenuItem("About");
         
        
        //Add components to popup menu
        popup.add(About);
        
        


        
        
        trayIcon.setPopupMenu(popup);
         
        trayIcon.setToolTip("Server Chat");
        
        try {
            tray.add(trayIcon);
        } catch (AWTException e) {
            System.out.println("TrayIcon could not be added.");
            return;
        }
        
        trayIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
           if(SC==null) {CA.setVisible(true);}
           else { SC.setVisible(true);}
            
            }
             
        });
        
        About.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            	Aboutshow();
                   
            } 
        });
        
        
        
        
        
        
        
        
        
        ActionListener listener = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                MenuItem item = (MenuItem)e.getSource();
                //TrayIcon.MessageType type = null;
                System.out.println(item.getLabel());
                if ("Error".equals(item.getLabel())) {
                    //type = TrayIcon.MessageType.ERROR;
                    trayIcon.displayMessage("Sun TrayIcon Demo",
                            "This is an error message", TrayIcon.MessageType.ERROR);
                    
                } else if ("Warning".equals(item.getLabel())) {
                    //type = TrayIcon.MessageType.WARNING;
                    trayIcon.displayMessage("Sun TrayIcon Demo",
                            "This is a warning message", TrayIcon.MessageType.WARNING);
                    
                } else if ("Info".equals(item.getLabel())) {
                    //type = TrayIcon.MessageType.INFO;
                    trayIcon.displayMessage("Sun TrayIcon Demo",
                            "This is an info message", TrayIcon.MessageType.INFO);
                    
                } else if ("None".equals(item.getLabel())) {
                    //type = TrayIcon.MessageType.NONE;
                    trayIcon.displayMessage("Sun TrayIcon Demo",
                            "This is an ordinary message", TrayIcon.MessageType.NONE);
                }
            }
        };
        
     
         
        trayIcon.setImageAutoSize(true);
    }
 
    
    static PopupMenu popup = new PopupMenu();
    
    public static void Aboutshow(){
    	
    	String s="<html></head><body><div align=center><font size='6' color='#0000FF' face='Times New Roman'><B><U>Author:</U></B></font></div><div align=center><font size='5' color='#000000' face='Times New Roman'><B>Elhacen Ely</B></font></div><div align=center><font size='4' face='Times New Roman'><B>e.elhacen@yahoo.com</B></font></div></body></html>";
    	JOptionPane.showMessageDialog(null,s,"About",1);
    }
}
